sudo: required # this specifices that we need sudo permission to travis for running docker
services:
  - docker

before_install:
  - docker build -t kinaanaamir/docker-react -f Dockerfile.dev .

# script sections contains all the different commands we need for the test to run
script:
  - docker run -e CI=true kinaanaamir/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react" # name of the in AWS
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-306476627547" # travis takes all the files in the git repository and zip them up and place them in bucket_name (s3) which is a harddrive of aws. Then it informs elasticbeanstallk to reeploy using the new code.
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY